import os
import asyncio
import unittest
from unittest.mock import AsyncMock, patch, MagicMock
from core.orchestration.central_brain import CentralBrain
from core.memory.shared_context_v2 import SharedContextV2 as SharedContext
from core.reporting import EnterpriseReporter
from core.intelligence.osint_engine import Employee
from core.intelligence.subdomain_enum import Subdomain

class TestCompleteE2EFlow(unittest.TestCase):
    """End-to-End Test for AntiGravity CentralBrain with & without OSINT."""

    def setUp(self):
        self.target = "https://example.com"
        self.scope = {"domains": ["example.com"], "max_tier": "POC"}

    @patch("core.central_brain.LLMClient.get")
    def test_e2e_with_osint_enabled(self, mock_llm_get):
        """Test full pipeline execution when OSINT is enabled."""
        os.environ["ENABLE_OSINT"] = "true"

        mock_res = MagicMock()
        mock_res.content = '{"action": "phase_complete"}'
        mock_llm = MagicMock()
        mock_llm.generate_response = AsyncMock(return_value=mock_res)
        mock_llm.generate = AsyncMock(return_value="Executive summary generated by LLM.")
        mock_llm_get.return_value = mock_llm

        brain = CentralBrain(target=self.target, scope=self.scope)

        # Mock sub-methods that make real network calls
        brain.tools.validate_tools = AsyncMock()
        brain._capture_requests = AsyncMock()
        brain._persist_captured_requests = AsyncMock()
        brain._run_phase_osint_reconnaissance = AsyncMock()
        brain._run_phase_deep_reconnaissance = AsyncMock()

        # Run the brain pipeline asynchronously
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(brain.run())
        finally:
            loop.close()

        # Assertions
        self.assertEqual(brain.ctx.target, self.target)
        self.assertTrue(os.getenv("ENABLE_OSINT") == "true")
        brain._run_phase_osint_reconnaissance.assert_called_once()
        
        # Verify report generation succeeded
        generated_reports = list(brain.report_dir.glob("*.json")) + list(brain.report_dir.glob("*.html"))
        self.assertTrue(len(generated_reports) > 0)

    @patch("core.central_brain.LLMClient.get")
    def test_e2e_with_osint_disabled(self, mock_llm_get):
        """Test full pipeline execution when OSINT is disabled via ENABLE_OSINT=false."""
        os.environ["ENABLE_OSINT"] = "false"

        mock_res = MagicMock()
        mock_res.content = '{"action": "phase_complete"}'
        mock_llm = MagicMock()
        mock_llm.generate_response = AsyncMock(return_value=mock_res)
        mock_llm.generate = AsyncMock(return_value="Executive summary generated by LLM.")
        mock_llm_get.return_value = mock_llm

        brain = CentralBrain(target=self.target, scope=self.scope)

        # Mock sub-methods that make real network calls
        brain.tools.validate_tools = AsyncMock()
        brain._capture_requests = AsyncMock()
        brain._persist_captured_requests = AsyncMock()
        brain._run_phase_osint_reconnaissance = AsyncMock()
        brain._run_phase_deep_reconnaissance = AsyncMock()

        # Run the brain pipeline asynchronously
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(brain.run())
        finally:
            loop.close()

        # Assertions
        self.assertEqual(brain.ctx.target, self.target)
        self.assertFalse(os.getenv("ENABLE_OSINT") == "true")
        brain._run_phase_osint_reconnaissance.assert_not_called()
        
        # Verify report generation succeeded without OSINT data
        generated_reports = list(brain.report_dir.glob("*.json")) + list(brain.report_dir.glob("*.html"))
        self.assertTrue(len(generated_reports) > 0)
        
        # Reset environment
        os.environ["ENABLE_OSINT"] = "true"

    def test_shared_context_state_flow(self):
        """Test thread-safe state sharing across pipeline modules."""
        ctx = SharedContext(target=self.target)
        
        # Update OSINT data
        ctx.update("discovered_employees", [
            Employee("Jane Doe", "jane@example.com", "DevOps", "example.com", "github", 0.95, "2026-08-28")
        ])
        ctx.update("discovered_subdomains", [
            Subdomain("api.example.com", "example.com", ["1.1.1.1"], None, "Cloudflare", None, "Let's Encrypt", None, None, 200, "API", [], "crt.sh", 0.9, "2026-08-28")
        ])

        # Verify getters
        self.assertEqual(len(ctx.get("discovered_employees", [])), 1)
        self.assertEqual(len(ctx.get("discovered_subdomains", [])), 1)
        self.assertEqual(ctx.get("non_existent_key", "default_val"), "default_val")

        # Test Reporter building HTML with this context
        reporter = EnterpriseReporter(ctx)
        html_out = reporter.build_html("Executive Summary Test")
        self.assertIn("jane@example.com", html_out)
        self.assertIn("api.example.com", html_out)

if __name__ == "__main__":
    unittest.main()
