
import html
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

SEV_WEIGHT = {"CRITICAL": 10.0, "HIGH": 7.0, "MEDIUM": 4.0, "LOW": 1.0, "INFO": 0.2}
SEV_COLOR = {"CRITICAL": "#b00020", "HIGH": "#d9531e", "MEDIUM": "#c9a227",
             "LOW": "#2e7d32", "INFO": "#607d8b"}

# ATT&CK tactic column order for the heatmap
TACTIC_ORDER = [
    "Initial Access", "Execution", "Persistence", "Privilege Escalation",
    "Credential Access", "Discovery", "Lateral Movement", "Collection",
    "Command and Control", "Exfiltration", "Impact",
]

MANDATORY_DISCLAIMER = (
    "This report is generated by an automated security validation framework. "
    "All findings require manual expert verification before remediation action is taken."
)


def mask_sensitive_data(text: str, enabled: bool = True) -> str:
    if not enabled or not text:
        return text or ""

    import re
    s = str(text)

    # ── AWS ──
    s = re.sub(r'\b(AKIA)[A-Z0-9]+?([A-Z0-9]{7})\b', r'\1************\2', s)
    # AWS secret access key (40 chars b64/hex-ish preceded by aws_secret markers)
    s = re.sub(r'(?i)(aws[_-]?secret[_-]?access[_-]?key\s*[:=]\s*[\'"]?)[A-Za-z0-9/+=]{30,}',
                r'\1[MASKED]', s)

    # ── GitHub / GitLab ──
    s = re.sub(r'\bghp_[A-Za-z0-9]{20,}\b', '[MASKED_GH_PAT]', s)
    s = re.sub(r'\bgho_[A-Za-z0-9]{20,}\b', '[MASKED_GH_OAUTH]', s)
    s = re.sub(r'\bghs_[A-Za-z0-9]{20,}\b', '[MASKED_GH_SERVER]', s)
    s = re.sub(r'\bglpat-[A-Za-z0-9_-]{20,}\b', '[MASKED_GL_PAT]', s)

    # ── OpenAI / Stripe / SendGrid / Slack ──
    s = re.sub(r'\bsk-[A-Za-z0-9]{20,}\b', '[MASKED_SK]', s)
    # Stripe secret/restricted keys: sk_live_/sk_test_/rk_live_/rk_test_ (underscore form).
    s = re.sub(r'\b[sr]k_(live|test)_[A-Za-z0-9]{16,}\b', '[MASKED_STRIPE]', s)
    s = re.sub(r'\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b', '[MASKED_SENDGRID]', s)
    s = re.sub(r'\bxox[bpoa]-[A-Za-z0-9-]{10,}\b', '[MASKED_SLACK]', s)

    # ── JWT ──
    s = re.sub(r'\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b', '[MASKED_JWT]', s)

    # ── Google API keys ──
    s = re.sub(r'\bAIza[0-9A-Za-z_-]{35}\b', '[MASKED_GOOGLE_API]', s)

    # ── Emails ──
    def _mask_email(m):
        local, domain = m.group(1), m.group(2)
        if len(local) <= 2:
            masked_local = local[0] + "*" + (local[1:] if len(local) > 1 else "")
        else:
            masked_local = local[0] + "***" + local[-1]
        return f"{masked_local}@{domain}"

    s = re.sub(r'\b([a-zA-Z0-9._%+-]+)@([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})\b', _mask_email, s)

    # ── Phone (best-effort, doesn't mask 10-digit IDs by requiring a dial format) ──
    s = re.sub(r'\+?\d{1,3}[\s.-]?\(?\d{2,4}\)?[\s.-]?\d{3,4}[\s.-]?\d{3,4}', '[MASKED_PHONE]', s)

    # ── Credit card ──
    s = re.sub(r'\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13})\b', '[MASKED_CC]', s)

    # ── SSN (US) ──
    s = re.sub(r'\b\d{3}-\d{2}-\d{4}\b', '[MASKED_SSN]', s)

    # ── password/secret/token/apikey key=value assignments ──
    s = re.sub(r'(?i)(password|passwd|secret|api[_-]?key|token|access[_-]?token|refresh[_-]?token|session[_-]?id)\s*[:=]\s*[\'"]?([^\s\'";,]{3,})[\'"]?',
                r'\1=[MASKED]', s)

    # ── Bearer tokens in Authorization headers ──
    s = re.sub(r'(?i)(Bearer\s+)[A-Za-z0-9._~+/-]+=*', r'\1[MASKED]', s)

    # ── Private-key headers ──
    s = re.sub(
        r'-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----',
        '[MASKED_PRIVATE_KEY]', s)

    return s


class EncryptedTrendStore:

    def __init__(self):
        self._init_db()

    def _init_db(self):
        from core.memory.database import DatabaseManager
        try:
            with DatabaseManager.get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute("""
                        CREATE TABLE IF NOT EXISTS scan_history_encrypted (
                            id SERIAL PRIMARY KEY,
                            timestamp TEXT NOT NULL,
                            target TEXT NOT NULL,
                            encrypted_data BYTEA NOT NULL
                        )
                    """)
                    conn.commit()
        except Exception as e:
            logger.error(f"EncryptedTrendStore init failed: {e}")

    def _encrypt(self, data: bytes) -> bytes:
        from core.security.encryption import encrypt
        return encrypt(data)

    def _decrypt(self, blob: bytes) -> bytes:
        from core.security.encryption import decrypt
        return decrypt(blob)

    def record_scan(self, target: str, severity_counts: Dict[str, int], critical_count: int, risk_score: float):
        import json, time
        from core.memory.database import DatabaseManager
        payload = {
            "target": target,
            "counts": severity_counts,
            "critical_count": critical_count,
            "risk_score": risk_score,
            "timestamp": time.time()
        }
        raw_bytes = json.dumps(payload).encode("utf-8")
        try:
            enc_blob = self._encrypt(raw_bytes)
        except Exception as e:
            logger.error(f"EncryptedTrendStore encrypt failed: {e}")
            return
        ts = datetime.now().isoformat()
        try:
            with DatabaseManager.get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute("INSERT INTO scan_history_encrypted (timestamp, target, encrypted_data) VALUES (%s, %s, %s)",
                                 (ts, target, enc_blob))
                    conn.commit()
        except Exception as e:
            logger.error(f"EncryptedTrendStore record_scan failed: {e}")

    def get_target_history(self, target: str) -> List[Dict]:
        import json
        from core.memory.database import DatabaseManager
        records = []
        try:
            with DatabaseManager.get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute("SELECT encrypted_data FROM scan_history_encrypted WHERE target = %s ORDER BY id ASC", (target,))
                    for row in cursor.fetchall():
                        try:
                            dec_bytes = self._decrypt(bytes(row[0]))
                            records.append(json.loads(dec_bytes.decode("utf-8")))
                        except Exception:
                            # Row was encrypted with the old XOR scheme or is
                            # corrupt — skip silently. Records will rebuild
                            # naturally as new scans complete.
                            continue
        except Exception as e:
            logger.error(f"EncryptedTrendStore get_target_history failed: {e}")
        return records

    def get_average_critical(self, target: str) -> float:
        history = self.get_target_history(target)
        if not history:
            return 0.0
        crits = [h.get("critical_count", 0) for h in history]
        return sum(crits) / len(crits)


def compare_industry_benchmark(counts: Dict[str, int], industry: str = None, csv_path: str = "data/industry_benchmarks.csv") -> str:
    import csv
    ind_clean = (industry or "default").strip().lower()
    benchmarks = {}
    path = Path(csv_path)
    if path.exists():
        try:
            with open(path, mode="r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    benchmarks[row["industry"].strip().lower()] = {
                        "critical": float(row.get("critical_avg", 8.0)),
                        "high": float(row.get("high_avg", 30.0)),
                        "medium": float(row.get("medium_avg", 20.0)),
                        "low": float(row.get("low_avg", 10.0)),
                    }
        except Exception:
            pass

    bench = benchmarks.get(ind_clean) or benchmarks.get("default") or {
        "critical": 8.0, "high": 30.0, "medium": 20.0, "low": 10.0
    }

    crit = counts.get("CRITICAL", 0)
    high = counts.get("HIGH", 0)

    msg = []
    if crit <= bench["critical"]:
        msg.append(f"Your critical findings ({crit}) are at or below the {ind_clean} industry average ({int(bench['critical'])}). Good job.")
    else:
        msg.append(f"Your critical findings ({crit}) exceed the {ind_clean} industry average ({int(bench['critical'])}). Review recommended.")

    if high <= bench["high"]:
        msg.append(f"Your high findings ({high}) are below the {ind_clean} industry average ({int(bench['high'])}).")
    else:
        msg.append(f"Your high findings ({high}) exceed the average ({int(bench['high'])}). Review recommended.")

    return " ".join(msg)


def generate_severity_chart(counts: Dict[str, int], previous_critical_avg: float = 0.0) -> Dict[str, str]:
    import base64
    severities = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    values = [counts.get(s, 0) for s in severities]
    colors = [SEV_COLOR.get(s, "#607d8b") for s in severities]

    crit_count = counts.get("CRITICAL", 0)
    if previous_critical_avg > 0 and crit_count > previous_critical_avg:
        trend_indicator = "▲"  # red up indicator
    elif previous_critical_avg > 0 and crit_count < previous_critical_avg:
        trend_indicator = "▼"  # green down indicator
    else:
        trend_indicator = "►"

    base64_png = ""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import io

        fig, ax = plt.subplots(figsize=(6, 2.8))
        y_pos = list(range(len(severities)))
        ax.barh(y_pos, values, color=colors, align="center")
        ax.set_yticks(y_pos)
        ax.set_yticklabels(severities)
        ax.invert_yaxis()
        ax.set_xlabel("Finding Count")
        ax.set_title(f"Severity Distribution ({trend_indicator} Critical Trend)")

        for i, v in enumerate(values):
            ax.text(v + 0.1, i, str(v), va="center", fontweight="bold")

        plt.tight_layout()
        buf = io.BytesIO()
        plt.savefig(buf, format="png", dpi=100)
        plt.close(fig)
        buf.seek(0)
        base64_png = base64.b64encode(buf.read()).decode("utf-8")
    except Exception as e:
        logger.warning(f"Matplotlib chart generation fallback: {e}")

    return {
        "base64_png": base64_png,
        "trend_indicator": trend_indicator
    }


def generate_key_metrics_table(vulnerabilities: List[Dict], retest_results: List[Dict] = None, historical_patches: List[Dict] = None) -> str:
    total = len(vulnerabilities)
    if total == 0:
        return (
            "| Metric | Value |\n"
            "| --- | --- |\n"
            "| Mean Time to Remediation (MTTR) | 0.0 Days |\n"
            "| % Public Exploit Available | 0.0% |\n"
            "| % Reproducible Findings | 0.0% |\n"
        )

    public_exploit_count = sum(1 for v in vulnerabilities if v.get("has_exploit") or v.get("public_exploit") or "exploit" in str(v.get("details", "")).lower())
    pct_exploit = (public_exploit_count / total) * 100.0

    if retest_results:
        reproducible_count = sum(1 for r in retest_results if r.get("reproducible") or r.get("status") == "CONFIRMED")
    else:
        reproducible_count = sum(1 for v in vulnerabilities if v.get("status", "CONFIRMED").upper() in ("CONFIRMED", "REPRODUCIBLE"))
    pct_reproducible = (reproducible_count / total) * 100.0

    mttr_days = 14.5
    if historical_patches:
        durations = [float(p["days_to_patch"]) for p in historical_patches if "days_to_patch" in p]
        if durations:
            mttr_days = sum(durations) / len(durations)

    return (
        "| Metric | Value |\n"
        "| --- | --- |\n"
        f"| Mean Time to Remediation (MTTR) | {mttr_days:.1f} Days |\n"
        f"| % Public Exploit Available | {pct_exploit:.1f}% |\n"
        f"| % Reproducible Findings | {pct_reproducible:.1f}% |\n"
    )


class ExecutiveSummaryGenerator:

    def __init__(self, template_path: str = "templates/executive_summary.jinja2"):
        self.template_path = Path(template_path)

    def render(self, ctx, industry: str = None, mask_sensitive: bool = True) -> Dict[str, str]:
        import jinja2
        import jinja2.sandbox

        vulns = getattr(ctx, "vulnerabilities", []) or []
        counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
        for v in vulns:
            sev = str(v.get("severity", "MEDIUM")).upper()
            counts[sev] = counts.get(sev, 0) + 1

        total_findings = len(vulns)
        crit = counts["CRITICAL"]
        high = counts["HIGH"]
        med = counts["MEDIUM"]
        low = counts["LOW"]

        # Risk score formula: (Critical*10 + High*5 + Medium*2) / total_findings
        overall_risk_score = round((crit * 10.0 + high * 5.0 + med * 2.0) / max(1, total_findings), 1)

        # Top 3 risks
        sorted_vulns = sorted(vulns, key=lambda x: SEV_WEIGHT.get(str(x.get("severity", "")).upper(), 0), reverse=True)
        top_3 = []
        for v in sorted_vulns[:3]:
            sev_w = SEV_WEIGHT.get(str(v.get("severity", "")).upper(), 1.0)
            top_3.append({
                "severity": str(v.get("severity", "MEDIUM")).upper(),
                "title": mask_sensitive_data(str(v.get("title", v.get("type", "Security Finding"))), mask_sensitive),
                "cve_id": str(v.get("cve", v.get("cve_id", ""))),
                "description": mask_sensitive_data(str(v.get("details", v.get("description", "")))[:200], mask_sensitive),
                "risk_score": round(sev_w, 1)
            })

        remediation_hours = crit * 16 + high * 8 + med * 4 + low * 2

        bullets = []
        if crit > 0:
            bullets.append(f"Critical: {crit} high-severity security vulnerabilities identified requiring urgent remediation.")
        if high > 0:
            bullets.append(f"High: {high} vulnerabilities present substantial risk to system confidentiality/integrity.")
        if total_findings == 0:
            bullets.append("No high-risk vulnerabilities identified during assessment.")
        else:
            bullets.append(f"Total {total_findings} findings identified across active scope targets.")

        benchmark_msg = compare_industry_benchmark(counts, industry)

        if self.template_path.exists():
            template_str = self.template_path.read_text(encoding="utf-8")
        else:
            template_str = (
                "EXECUTIVE ASSESSMENT SUMMARY\n"
                "Target: {{ target_name }}\n"
                "Date: {{ scan_date }}\n"
                "Risk Score: {{ overall_risk_score }}\n"
                "Total Findings: {{ total_findings }}\n\n"
                "{{ mandatory_disclaimer }}\n"
            )

        # Use SandboxedEnvironment so a maliciously modified template on disk
        # can't reach dangerous attributes (`__class__`, `__subclasses__`, etc.)
        # to escape into arbitrary Python execution — the classic SSTI vector.
        # Autoescape is enabled so rendered fields can't break HTML structure.
        _sandbox_env = jinja2.sandbox.SandboxedEnvironment(autoescape=True)
        template = _sandbox_env.from_string(template_str)
        rendered_text = template.render(
            target_name=mask_sensitive_data(str(getattr(ctx, "target", "Target")), mask_sensitive),
            scan_date=datetime.now().strftime("%Y-%m-%d"),
            total_findings=total_findings,
            critical_count=crit,
            high_count=high,
            medium_count=med,
            low_count=low,
            overall_risk_score=overall_risk_score,
            remediation_effort_estimate=remediation_hours,
            top_3_risks=top_3,
            executive_bullet_points=bullets,
            benchmark_comparison=benchmark_msg,
            mandatory_disclaimer=MANDATORY_DISCLAIMER
        )

        html_summary = f"<div class='exec-summary'><pre>{html.escape(rendered_text)}</pre></div>"

        return {
            "text": rendered_text,
            "html": html_summary,
            "risk_score": overall_risk_score,
            "remediation_hours": remediation_hours
        }


class EnterpriseReporter:

    def __init__(self, ctx, report_dir: str = None,
                 active_frameworks=None):
        self.ctx = ctx
        from core.common.reports_config import reports_enabled, reports_dir
        self._reports_enabled = reports_enabled()
        if report_dir is None:
            report_dir = str(reports_dir())
        self.report_dir = Path(report_dir)
        if self._reports_enabled:
            self.report_dir.mkdir(parents=True, exist_ok=True)
        self.active_frameworks = active_frameworks

    def _compliance_html(self) -> str:
        try:
            from core.compliance import ComplianceReporter
        except Exception:       # noqa: BLE001
            return "<p class='muted'>Compliance module unavailable.</p>"
        summary = ComplianceReporter(self.active_frameworks).build(
            self.ctx.vulnerabilities)
        if not summary.get("frameworks"):
            return "<p class='muted'>No frameworks selected.</p>"
        blocks = []
        for fw, data in summary["frameworks"].items():
            rows = "".join(
                f"<tr><td>{html.escape(c['control_id'])}</td>"
                f"<td>{html.escape(c['control_title'])}</td>"
                f"<td style='color:{'#b00020' if c['status']=='FAIL' else '#2e7d32'};"
                f"font-weight:600'>{c['status']}</td>"
                f"<td>{c['finding_count']}</td></tr>"
                for c in data["controls"])
            blocks.append(
                f"<h4>{html.escape(data['name'])} "
                f"<span class='muted'>({data['controls_failed']} fail / "
                f"{data['controls_total']})</span></h4>"
                f"<table><thead><tr><th>Control</th><th>Title</th>"
                f"<th>Status</th><th>Findings</th></tr></thead>"
                f"<tbody>{rows}</tbody></table>")
        return "".join(blocks)

    # ── risk scoring ──

    def risk_score(self) -> Dict:
        counts = {k: 0 for k in SEV_WEIGHT}
        for v in self.ctx.vulnerabilities:
            sev = str(v.get("severity", "MEDIUM")).upper()
            counts[sev] = counts.get(sev, 0) + 1
        raw = sum(SEV_WEIGHT.get(s, 0) * n for s, n in counts.items())
        # Normalize with diminishing returns
        score = min(100.0, raw)
        rating = ("CRITICAL" if score >= 80 else "HIGH" if score >= 50
                  else "MEDIUM" if score >= 20 else "LOW")
        # Floor the rating by the worst single finding: one CRITICAL is never
        # an overall "LOW" risk regardless of the aggregate score.
        order = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
        floor = "LOW"
        if counts.get("CRITICAL"):
            floor = "HIGH"
        elif counts.get("HIGH"):
            floor = "MEDIUM"
        if order.index(rating) < order.index(floor):
            rating = floor
        return {"score": round(score, 1), "rating": rating, "counts": counts}

    # ── HTML sections ──

    def _bar(self, counts: Dict[str, int]) -> str:
        total = max(1, sum(counts.values()))
        segs = []
        for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"):
            n = counts.get(sev, 0)
            if n:
                pct = 100 * n / total
                segs.append(
                    f'<div style="width:{pct:.1f}%;background:{SEV_COLOR[sev]};" '
                    f'title="{sev}: {n}">{n}</div>')
        return f'<div class="bar">{"".join(segs)}</div>'

    def _vuln_table(self) -> str:
        rows = []
        for v in sorted(self.ctx.vulnerabilities,
                        key=lambda x: SEV_WEIGHT.get(str(x.get("severity", "")).upper(), 0),
                        reverse=True):
            sev = str(v.get("severity", "MEDIUM")).upper()
            status = str(v.get("status", "CONFIRMED")).upper()
            status_bg = "#2e7d32" if status == "CONFIRMED" else "#c9a227"
            rows.append(
                f"<tr>"
                f'<td><span class="pill" style="background:{SEV_COLOR.get(sev,"#777")}">{html.escape(sev)}</span></td>'
                f'<td><span class="pill" style="background:{status_bg}">{html.escape(status)}</span></td>'
                f"<td>{html.escape(str(v.get('id','')))}</td>"
                f"<td>{html.escape(str(v.get('title', v.get('type',''))))}</td>"
                f"<td>{html.escape(str(v.get('location','')))}</td>"
                f"<td>{html.escape(str(v.get('details',''))[:300])}</td>"
                f"</tr>")
        if not rows:
            rows.append('<tr><td colspan="6">No vulnerabilities recorded.</td></tr>')
        return ("<table><thead><tr><th>Severity</th><th>Status</th><th>ID</th><th>Title</th>"
                "<th>Location</th><th>Details</th></tr></thead><tbody>"
                + "".join(rows) + "</tbody></table>")

    def _attack_path_svg(self) -> str:
        chains = self.ctx.attack_chains or []
        if isinstance(chains, dict):
            chains = list(chains.values()) if chains else []
        if not isinstance(chains, list):
            chains = []
        if not chains:
            return "<p class='muted'>No multi-step attack chains identified.</p>"
        svg_blocks = []
        for ci, chain in enumerate(chains[:6]):
            steps = chain.get("steps") or chain.get("path") or []
            if isinstance(steps, dict):
                steps = list(steps.values())
            labels = []
            for s in steps:
                if isinstance(s, dict):
                    labels.append(str(s.get("type") or s.get("vuln_id") or s.get("title") or "?"))
                else:
                    labels.append(str(s))
            if not labels:
                continue
            w = 20 + len(labels) * 170
            nodes = []
            for i, lab in enumerate(labels):
                x = 20 + i * 170
                nodes.append(
                    f'<rect x="{x}" y="25" rx="6" width="140" height="40" '
                    f'fill="#1e3a5f" stroke="#3d6ea5"/>'
                    f'<text x="{x+70}" y="50" fill="#fff" font-size="12" '
                    f'text-anchor="middle">{html.escape(lab[:18])}</text>')
                if i < len(labels) - 1:
                    ax = x + 140
                    nodes.append(
                        f'<line x1="{ax}" y1="45" x2="{ax+30}" y2="45" '
                        f'stroke="#3d6ea5" stroke-width="2" marker-end="url(#arw)"/>')
            svg_blocks.append(
                f'<div class="chain"><b>Chain #{ci+1}</b> '
                f'(score {chain.get("score","?")})'
                f'<svg width="{w}" height="90" xmlns="http://www.w3.org/2000/svg">'
                f'<defs><marker id="arw" markerWidth="8" markerHeight="8" refX="6" refY="3" '
                f'orient="auto"><path d="M0,0 L6,3 L0,6 Z" fill="#3d6ea5"/></marker></defs>'
                f'{"".join(nodes)}</svg></div>')
        return "".join(svg_blocks) or "<p class='muted'>No renderable chains.</p>"

    def _mitre_heatmap(self) -> str:
        mappings = self.ctx.mitre_mappings or []
        if not mappings:
            return "<p class='muted'>No ATT&CK techniques mapped.</p>"
        by_tactic: Dict[str, List[Dict]] = {}
        for m in mappings:
            by_tactic.setdefault(m.get("tactic", "Unknown"), []).append(m)
        cols = [t for t in TACTIC_ORDER if t in by_tactic]
        cols += [t for t in by_tactic if t not in cols]
        cells = []
        for t in cols:
            techs = by_tactic[t]
            intensity = min(1.0, len(techs) / 4.0)
            bg = f"rgba(176,0,32,{0.25 + 0.6*intensity:.2f})"
            items = "".join(
                f'<div class="tech" title="{html.escape(m.get("detection",""))}">'
                f'{html.escape(m.get("technique_id",""))} '
                f'{html.escape(m.get("name","")[:22])}</div>' for m in techs)
            cells.append(
                f'<div class="tcol"><div class="thead" style="background:{bg}">'
                f'{html.escape(t)} ({len(techs)})</div>{items}</div>')
        return f'<div class="heatmap">{"".join(cells)}</div>'

    def _remediation(self) -> str:
        rem = {
            "CRITICAL": "Immediate remediation required (patch/disable within 24-48h).",
            "HIGH": "Remediate in the current sprint; add compensating controls now.",
            "MEDIUM": "Schedule remediation; monitor for exploitation.",
            "LOW": "Track and remediate opportunistically.",
        }
        seen = {}
        for v in self.ctx.vulnerabilities:
            sev = str(v.get("severity", "MEDIUM")).upper()
            seen.setdefault(sev, []).append(v.get("title", v.get("type", "?")))
        blocks = []
        for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
            if sev in seen:
                items = "".join(f"<li>{html.escape(str(t))}</li>" for t in seen[sev][:15])
                blocks.append(
                    f'<h4 style="color:{SEV_COLOR[sev]}">{sev} — {rem[sev]}</h4>'
                    f"<ul>{items}</ul>")
        return "".join(blocks) or "<p class='muted'>No remediation items.</p>"

    def _poc_reproduction_table(self) -> str:
        vulns = self.ctx.vulnerabilities or []
        if not vulns:
            return "<p class='muted'>No confirmed vulnerabilities requiring POC reproduction.</p>"

        rows = []
        for i, v in enumerate(vulns, 1):
            sev = str(v.get("severity", "MEDIUM")).upper()
            title = str(v.get("title", v.get("type", f"Vulnerability_{i}")))
            url = str(v.get("url", v.get("endpoint", v.get("location", self.ctx.target))))
            method = str(v.get("method", "GET")).upper()
            payload = v.get("payload", "")

            # Shell-safe rendering: `shlex.quote` produces a single-quoted
            # token that shell will re-interpret literally. Without this, a
            # payload containing `'; rm -rf ~; #` (attacker- or vuln-response-
            # controlled) would execute when the operator pastes the command
            # into a terminal — a supply-chain foot-gun in the delivered
            # report. Using the safer form is essentially free.
            import shlex
            if method == "POST":
                data_val = str(payload)
                curl_cmd = f"curl -k -i -X POST {shlex.quote(url)} -d {shlex.quote(data_val)}"
            else:
                curl_cmd = f"curl -k -i -X GET {shlex.quote(url)}"

            rows.append(
                f"<tr>"
                f"<td>{i}</td>"
                f'<td><span class="pill" style="background:{SEV_COLOR.get(sev, "#777")}">{html.escape(sev)}</span></td>'
                f"<td><b>{html.escape(title)}</b></td>"
                f"<td><code>{html.escape(curl_cmd)}</code></td>"
                f"</tr>"
            )

        poc_links = (
            "<p><b>Generated Standalone Exploits:</b> "
            "<a href='poc_reproduce.py' target='_blank'>poc_reproduce.py (Python 3)</a> &nbsp;|&nbsp; "
            "<a href='poc_reproduce.sh' target='_blank'>poc_reproduce.sh (Bash/cURL)</a> &nbsp;|&nbsp; "
            "<a href='poc_summary.md' target='_blank'>poc_summary.md (Markdown Guide)</a></p>"
        )

        return (
            poc_links +
            "<table><thead><tr><th>#</th><th>Severity</th><th>Vulnerability</th>"
            "<th>Reproduction Command (cURL)</th></tr></thead><tbody>"
            + "".join(rows) + "</tbody></table>"
        )

    # ── build ──

    def build_html(self, executive_summary: str = "") -> str:
        risk = self.risk_score()
        fp_count = len(getattr(self.ctx, "false_positives", []))
        meta_rows = (
            f"<tr><td>Target</td><td>{html.escape(str(self.ctx.target))}</td></tr>"
            f"<tr><td>Generated</td><td>{datetime.now().isoformat(timespec='seconds')}</td></tr>"
            f"<tr><td>Vulnerabilities</td><td>{len(self.ctx.vulnerabilities)}</td></tr>"
            f"<tr><td>Filtered False Positives</td><td>{fp_count}</td></tr>"
            f"<tr><td>Exploits run</td><td>{len(self.ctx.exploit_results)}</td></tr>"
            f"<tr><td>Agents</td><td>{len(self.ctx.agents_spawned)}</td></tr>"
        )
        exec_html = html.escape(executive_summary).replace("\n", "<br>") or \
            "<span class='muted'>No executive summary provided.</span>"
        full_html = f"""<!doctype html><html><head><meta charset="utf-8">
<title>Penetration Test Report — {html.escape(str(self.ctx.target))}</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;background:#f5f6f8;color:#1c2430}}
 header{{background:#12233b;color:#fff;padding:28px 40px}}
 header h1{{margin:0;font-size:22px}} header .sub{{opacity:.8;font-size:13px}}
 main{{max-width:1100px;margin:0 auto;padding:24px 40px}}
 section{{background:#fff;border:1px solid #e2e6ec;border-radius:8px;padding:20px 24px;margin:18px 0}}
 h2{{font-size:17px;border-bottom:2px solid #12233b;padding-bottom:6px}}
 table{{width:100%;border-collapse:collapse;font-size:13px}}
 th,td{{text-align:left;padding:7px 9px;border-bottom:1px solid #eef1f4;vertical-align:top}}
 th{{background:#f0f3f7}}
 .pill,.score{{color:#fff;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600}}
 .bar{{display:flex;height:26px;border-radius:5px;overflow:hidden;font-size:11px}}
 .bar div{{display:flex;align-items:center;justify-content:center;color:#fff}}
 .scorebox{{font-size:40px;font-weight:700}}
 .muted{{color:#8a94a3}} .chain{{margin:12px 0;overflow-x:auto}}
 .heatmap{{display:flex;gap:8px;overflow-x:auto}} .tcol{{min-width:150px}}
 .thead{{color:#fff;font-size:12px;font-weight:600;padding:6px;border-radius:5px;text-align:center}}
 .tech{{background:#eef1f4;margin:4px 0;padding:5px 6px;border-radius:4px;font-size:11px}}
 code{{background:#eef1f4;padding:2px 5px;border-radius:3px;font-family:Consolas,monospace;font-size:12px}}
</style></head><body>
<header><h1>Penetration Test Report</h1>
 <div class="sub">{html.escape(str(self.ctx.target))} · generated {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>
</header><main>
 <section><h2>Risk Overview</h2>
  <p><span class="score" style="background:{SEV_COLOR.get(risk['rating'],'#777')}">
   Overall risk: {risk['rating']}</span> &nbsp; <span class="scorebox">{risk['score']}</span><span class="muted">/100</span></p>
  {self._bar(risk['counts'])}
  <table>{meta_rows}</table>
 </section>
 <section><h2>Executive Summary</h2><p>{exec_html}</p></section>
 <section><h2>Findings</h2>{self._vuln_table()}</section>
 <section><h2>Exploit Proof of Concepts (POC)</h2>{self._poc_reproduction_table()}</section>
 <section><h2>Attack Path Visualization</h2>{self._attack_path_svg()}</section>
 <section><h2>MITRE ATT&amp;CK Heatmap</h2>{self._mitre_heatmap()}</section>
 <section><h2>Compliance Summary</h2>{self._compliance_html()}</section>
 <section><h2>Remediation</h2>{self._remediation()}</section>
</main></body></html>"""
        return self.add_osint_findings(full_html)

    def generate(self, executive_summary: str = "", stem: str = "") -> Dict[str, str]:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        stem = stem or f"report_{ts}"
        html_str = self.build_html(executive_summary)
        if not self._reports_enabled:
            return {"html_str": html_str}
        html_path = self.report_dir / f"{stem}.html"
        html_path.write_text(html_str, encoding="utf-8")
        logger.info(f"[Report] HTML report written: {html_path}")

        out = {"html": str(html_path)}
        pdf_path = self.report_dir / f"{stem}.pdf"
        # `renderer` tracks WHICH engine won so we can surface a degraded-quality
        # warning when we fall past the CSS-capable engines. Previously any
        # fallback lower than xhtml2pdf silently produced tag-stripped plain
        # text with a `.pdf` extension, and the operator only found out when
        # they opened the file. Now we log at WARN and stamp `out["pdf_engine"]`.
        renderer: Optional[str] = None
        try:
            from weasyprint import HTML as _WHTML   # optional dependency
            _WHTML(string=html_str).write_pdf(str(pdf_path))
            out["pdf"] = str(pdf_path)
            renderer = "weasyprint"
            logger.info(f"[Report] PDF report written via WeasyPrint: {pdf_path}")
        except Exception as e:      # noqa: BLE001
            logger.info(f"[Report] WeasyPrint PDF skipped: {e}")

        if renderer is None:
            try:
                from xhtml2pdf import pisa
                with open(pdf_path, "wb") as pdf_file:
                    pisa_status = pisa.CreatePDF(html_str, dest=pdf_file)
                if not pisa_status.err:
                    out["pdf"] = str(pdf_path)
                    renderer = "xhtml2pdf"
                    logger.info(f"[Report] PDF report written via xhtml2pdf fallback: {pdf_path}")
            except Exception as e:
                logger.info(f"[Report] xhtml2pdf fallback skipped: {e}")

        if renderer is None:
            try:
                import pdfkit
                pdfkit.from_string(html_str, str(pdf_path), options={"quiet": "", "encoding": "UTF-8"})
                out["pdf"] = str(pdf_path)
                renderer = "pdfkit"
                logger.info(f"[Report] PDF report written via pdfkit: {pdf_path}")
            except Exception as e:
                logger.info(f"[Report] pdfkit fallback skipped: {e}")

        if renderer is None:
            try:
                from fpdf import FPDF  # noqa: F401
                pdf = self._html_to_fpdf(html_str)
                pdf.output(str(pdf_path))
                out["pdf"] = str(pdf_path)
                renderer = "fpdf2"
                logger.warning(
                    "[Report] PDF written via fpdf2 fallback — HTML/CSS stripped, "
                    "no tables/charts/formatting. Install weasyprint (with "
                    "libgobject/cairo/pango) for full-fidelity reports. File: %s",
                    pdf_path,
                )
            except Exception as e:
                logger.info(f"[Report] fpdf2 fallback skipped: {e}")

        if renderer is None:
            logger.error(
                "[Report] No PDF renderer available. Install one of: "
                "weasyprint (recommended), xhtml2pdf, pdfkit (+ wkhtmltopdf), or fpdf2. "
                "Report will be delivered as HTML only.")
        else:
            out["pdf_engine"] = renderer
            out["pdf_degraded"] = renderer in ("fpdf2",)

        return out

    @staticmethod
    def _html_to_fpdf(html_str: str):
        from fpdf import FPDF
        import re as _re

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Strip HTML tags for text extraction
        text = _re.sub(r'<style[^>]*>.*?</style>', '', html_str, flags=_re.DOTALL)
        text = _re.sub(r'<script[^>]*>.*?</script>', '', text, flags=_re.DOTALL)
        text = _re.sub(r'<br\s*/?>', '\n', text, flags=_re.IGNORECASE)
        text = _re.sub(r'</?(p|div|tr|li|h[1-6])[^>]*>', '\n', text, flags=_re.IGNORECASE)
        text = _re.sub(r'<[^>]+>', '', text)
        text = _re.sub(r'&amp;', '&', text)
        text = _re.sub(r'&lt;', '<', text)
        text = _re.sub(r'&gt;', '>', text)
        text = _re.sub(r'&nbsp;', ' ', text)
        text = _re.sub(r'&#\d+;', '', text)
        text = _re.sub(r'\n{3,}', '\n\n', text)

        pdf.set_font("Helvetica", size=10)
        for line in text.split('\n'):
            line = line.strip()
            if not line:
                pdf.ln(3)
                continue
            try:
                pdf.multi_cell(0, 5, line)
            except Exception:
                safe = line.encode('latin-1', 'replace').decode('latin-1')
                pdf.multi_cell(0, 5, safe)

        return pdf


    def add_osint_findings(self, report_html: str) -> str:
        osint_findings = getattr(self.ctx, "osint_findings", {}) or {}
        
        employees_data = getattr(self.ctx, "discovered_employees", []) or osint_findings.get("employees", [])
        emp_rows = ""
        for emp in employees_data:
            name = getattr(emp, "name", "") or emp.get("name", "") if isinstance(emp, dict) else getattr(emp, "name", "")
            email = getattr(emp, "email", "") or emp.get("email", "") if isinstance(emp, dict) else getattr(emp, "email", "")
            role = getattr(emp, "role", "") or emp.get("role", "") if isinstance(emp, dict) else getattr(emp, "role", "")
            source = getattr(emp, "source", "") or emp.get("source", "") if isinstance(emp, dict) else getattr(emp, "source", "")
            emp_rows += f"<tr><td>{html.escape(str(email))}</td><td>{html.escape(str(role))}</td><td>{html.escape(str(source))}</td></tr>"
        if not emp_rows:
            emp_rows = "<tr><td colspan='3' class='muted'>No employees discovered.</td></tr>"

        creds_data = getattr(self.ctx, "leaked_credentials", []) or osint_findings.get("leaked_credentials", [])
        cred_rows = ""
        for cred in creds_data:
            svc = getattr(cred, "service", "") or cred.get("service", "") if isinstance(cred, dict) else getattr(cred, "service", "")
            sev = getattr(cred, "severity", "") or cred.get("severity", "") if isinstance(cred, dict) else getattr(cred, "severity", "")
            cred_rows += f"<tr><td>Credential Leak</td><td>{html.escape(str(svc))}</td><td><span class='pill' style='background:{SEV_COLOR.get(sev.upper(), '#777')}'>{html.escape(str(sev))}</span></td></tr>"
        if not cred_rows:
            cred_rows = "<tr><td colspan='3' class='muted'>No leaked credentials found.</td></tr>"

        subdomains_data = getattr(self.ctx, "discovered_subdomains", []) or osint_findings.get("subdomains", [])
        sub_rows = ""
        for sub in subdomains_data:
            name = getattr(sub, "name", "") or sub.get("name", "") if isinstance(sub, dict) else getattr(sub, "name", "")
            ips = getattr(sub, "ip_addresses", []) or sub.get("ip_addresses", []) if isinstance(sub, dict) else getattr(sub, "ip_addresses", [])
            cdn = getattr(sub, "cdn", "") or sub.get("cdn", "") if isinstance(sub, dict) else getattr(sub, "cdn", "")
            status = getattr(sub, "status_code", "") or sub.get("status_code", "") if isinstance(sub, dict) else getattr(sub, "status_code", "")
            ip_str = ", ".join(ips) if isinstance(ips, list) else str(ips)
            sub_rows += f"<tr><td>{html.escape(str(name))}</td><td>{html.escape(ip_str)}</td><td>{html.escape(str(cdn or 'Direct'))}</td><td>{html.escape(str(status or 'Active'))}</td></tr>"
        if not sub_rows:
            sub_rows = "<tr><td colspan='4' class='muted'>No subdomains enumerated.</td></tr>"

        threats_data = getattr(self.ctx, "threat_correlations", []) or osint_findings.get("threat_correlations", [])
        threat_rows = ""
        for th in threats_data:
            asset = th.get("asset", "") if isinstance(th, dict) else getattr(th, "asset", "")
            ttype = th.get("threat_type", "") if isinstance(th, dict) else getattr(th, "threat_type", "")
            sev = th.get("severity", "") if isinstance(th, dict) else getattr(th, "severity", "")
            sources = th.get("sources", []) if isinstance(th, dict) else getattr(th, "sources", [])
            src_str = ", ".join(sources) if isinstance(sources, list) else str(sources)
            threat_rows += f"<tr><td>{html.escape(str(asset))}</td><td>{html.escape(str(ttype))}</td><td><span class='pill' style='background:{SEV_COLOR.get(sev.upper(), '#777')}'>{html.escape(str(sev))}</span></td><td>{html.escape(src_str)}</td></tr>"
        if not threat_rows:
            threat_rows = "<tr><td colspan='4' class='muted'>No threat intelligence correlations.</td></tr>"

        osint_html = f"""
        <section class="osint-findings">
            <h2>OSINT Reconnaissance Findings</h2>
            
            <h3>Employee Discovery</h3>
            <table>
                <tr><th>Email</th><th>Role</th><th>Source</th></tr>
                {emp_rows}
            </table>
            
            <h3>Leaked Credentials</h3>
            <table>
                <tr><th>Type</th><th>Service</th><th>Severity</th></tr>
                {cred_rows}
            </table>
            
            <h3>Discovered Subdomains</h3>
            <table>
                <tr><th>Subdomain</th><th>IPs</th><th>CDN</th><th>Status</th></tr>
                {sub_rows}
            </table>
            
            <h3>Threat Intelligence</h3>
            <table>
                <tr><th>Asset</th><th>Threat Type</th><th>Severity</th><th>Sources</th></tr>
                {threat_rows}
            </table>
        </section>
        """
        
        # Inject at the LAST `</main>` only. A naive `str.replace` would corrupt
        # the page if any finding proof block happened to include the literal
        # substring `</main>` earlier in the document.
        idx = report_html.rfind('</main>')
        if idx == -1:
            # No </main> — append at the end and let the browser be forgiving.
            return report_html + osint_html
        return report_html[:idx] + osint_html + report_html[idx:]
